import type {
  Campeonato,
  ClassificacaoItem,
  HistoricalPerformance,
  Participante,
  StandingEntry,
  Tournament,
  TournamentParticipant,
} from "@/types/tournament";
import type { Match } from "@/types/match";
import type { VideoHighlight } from "@/types/video";
import type { Trophy } from "@/types/trophy";

export const bootMessages = [
  "conectando arena",
  "sincronizando campeonatos",
  "carregando jogadores",
  "validando trofeus",
];

export const tournamentFormats = [
  { label: "Pontos corridos", value: "league" },
  { label: "Fase de grupos", value: "groups" },
  { label: "Mata-mata", value: "knockout" },
  { label: "Grupos + mata-mata", value: "groups_knockout" },
] as const;

export const tournamentMatchModes = [
  { label: "Jogo único", value: "single_game" },
  { label: "Casa e\u00A0fora", value: "home_away" },
] as const;

export const classificationCriteriaOptions = [
  { label: "Pontos", value: "points" },
  { label: "Saldo", value: "goal_difference" },
  { label: "Gols pro", value: "goals_for" },
  { label: "Vitorias", value: "wins" },
  { label: "Empates", value: "draws" },
  { label: "Derrotas", value: "losses" },
  { label: "Confronto direto", value: "head_to_head" },
] as const;

export const sampleTournament: Tournament = {
  id: "arena-2026-open",
  name: "Arena Football Master Series",
  format: "groups_knockout",
  matchMode: "single_game",
  status: "in_progress",
  rules: "Mandante cria a sala. Resultados precisam de aprovacao do organizador.",
  creatorId: "user-organizer",
  startDate: "2026-03-22",
  allowVideos: true,
  allowGoalAward: true,
  coverUrl: null,
  createdAt: "2026-03-22T00:00:00Z",
};

export const sampleCampeonato: Campeonato = {
  id: "arena-2026-open",
  nome: "Arena Football Master Series",
  status: "ativo",
  criadoEm: "2026-03-22T00:00:00Z",
  temporada: "2026-Q1",
  modoConfronto: "single_game",
  participantes: [
    {
      id: "participant-1",
      nome: "Matheus",
      time: "Corinthians",
      whatsapp: "11999999999",
    },
    {
      id: "participant-2",
      nome: "João",
      time: "São Paulo",
      whatsapp: "11999999998",
    },
  ],
  rodadas: [],
  classificacao: [
    {
      participanteId: "participant-1",
      nome: "Matheus",
      time: "Corinthians",
      pontos: 3,
      jogos: 1,
      vitorias: 1,
      empates: 0,
      derrotas: 0,
      golsPro: 2,
      golsContra: 0,
      saldo: 2,
    },
    {
      participanteId: "participant-2",
      nome: "João",
      time: "São Paulo",
      pontos: 0,
      jogos: 1,
      vitorias: 0,
      empates: 0,
      derrotas: 1,
      golsPro: 0,
      golsContra: 2,
      saldo: -2,
    },
  ],
};

export const sampleParticipants: TournamentParticipant[] = [
  {
    id: "participant-1",
    tournamentId: sampleTournament.id,
    userId: "user-organizer",
    teamName: "Corinthians",
    groupName: "Grupo A",
    isOrganizer: true,
    displayName: "Matheus",
    teamBadgeUrl: null,
    stadiumImageUrl: null,
  },
  {
    id: "participant-2",
    tournamentId: sampleTournament.id,
    userId: "user-2",
    teamName: "Bragantino",
    groupName: "Grupo A",
    isOrganizer: false,
    displayName: "Bruno",
    teamBadgeUrl: null,
    stadiumImageUrl: null,
  },
  {
    id: "participant-3",
    tournamentId: sampleTournament.id,
    userId: "user-3",
    teamName: "Internacional",
    groupName: "Grupo A",
    isOrganizer: false,
    displayName: "Lucas",
    teamBadgeUrl: null,
    stadiumImageUrl: null,
  },
  {
    id: "participant-4",
    tournamentId: sampleTournament.id,
    userId: "user-4",
    teamName: "Young Boys",
    groupName: "Grupo A",
    isOrganizer: false,
    displayName: "Diego",
    teamBadgeUrl: null,
    stadiumImageUrl: null,
  },
  {
    id: "participant-5",
    tournamentId: sampleTournament.id,
    userId: "user-5",
    teamName: "Chelsea",
    groupName: "Grupo B",
    isOrganizer: false,
    displayName: "Rafael",
    teamBadgeUrl: null,
    stadiumImageUrl: null,
  },
  {
    id: "participant-6",
    tournamentId: sampleTournament.id,
    userId: "user-6",
    teamName: "Flamengo",
    groupName: "Grupo B",
    isOrganizer: false,
    displayName: "Felipe",
    teamBadgeUrl: null,
    stadiumImageUrl: null,
  },
  {
    id: "participant-7",
    tournamentId: sampleTournament.id,
    userId: "user-7",
    teamName: "Borussia",
    groupName: "Grupo B",
    isOrganizer: false,
    displayName: "Andre",
    teamBadgeUrl: null,
    stadiumImageUrl: null,
  },
  {
    id: "participant-8",
    tournamentId: sampleTournament.id,
    userId: "user-8",
    teamName: "Midtjylland",
    groupName: "Grupo B",
    isOrganizer: false,
    displayName: "Thiago",
    teamBadgeUrl: null,
    stadiumImageUrl: null,
  },
];

export const sampleMatches: Match[] = [
  {
    id: "match-1",
    tournamentId: sampleTournament.id,
    round: 1,
    phase: "Fase de grupos",
    homeParticipantId: "participant-1",
    awayParticipantId: "participant-2",
    homeGoals: null,
    awayGoals: null,
    roomCreatorParticipantId: "participant-1",
    deadlineAt: "2026-04-06T23:59:00Z",
    status: "pending",
  },
];

export const sampleStandings: StandingEntry[] = [
  {
    participantId: "participant-1",
    played: 3,
    points: 9,
    wins: 3,
    draws: 0,
    losses: 0,
    goalsFor: 8,
    goalsAgainst: 2,
    goalDifference: 6,
  },
  {
    participantId: "participant-2",
    played: 3,
    points: 6,
    wins: 2,
    draws: 0,
    losses: 1,
    goalsFor: 6,
    goalsAgainst: 4,
    goalDifference: 2,
  },
  {
    participantId: "participant-3",
    played: 3,
    points: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 4,
    goalsAgainst: 6,
    goalDifference: -2,
  },
  {
    participantId: "participant-4",
    played: 3,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsFor: 2,
    goalsAgainst: 8,
    goalDifference: -6,
  },
  {
    participantId: "participant-5",
    played: 3,
    points: 7,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsFor: 7,
    goalsAgainst: 3,
    goalDifference: 4,
  },
  {
    participantId: "participant-6",
    played: 3,
    points: 4,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsFor: 5,
    goalsAgainst: 5,
    goalDifference: 0,
  },
  {
    participantId: "participant-7",
    played: 3,
    points: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 4,
    goalsAgainst: 6,
    goalDifference: -2,
  },
  {
    participantId: "participant-8",
    played: 3,
    points: 1,
    wins: 0,
    draws: 1,
    losses: 2,
    goalsFor: 3,
    goalsAgainst: 5,
    goalDifference: -2,
  },
];

export const sampleHistoricalPerformance: HistoricalPerformance[] = [
  {
    userId: "user-organizer",
    championshipsPlayed: 6,
    matchesPlayed: 34,
    wins: 23,
    draws: 5,
    losses: 6,
    titles: 2,
  },
  {
    userId: "user-2",
    championshipsPlayed: 5,
    matchesPlayed: 29,
    wins: 17,
    draws: 4,
    losses: 8,
    titles: 1,
  },
  {
    userId: "user-3",
    championshipsPlayed: 4,
    matchesPlayed: 24,
    wins: 11,
    draws: 5,
    losses: 8,
    titles: 0,
  },
  {
    userId: "user-4",
    championshipsPlayed: 4,
    matchesPlayed: 22,
    wins: 8,
    draws: 4,
    losses: 10,
    titles: 0,
  },
  {
    userId: "user-5",
    championshipsPlayed: 7,
    matchesPlayed: 40,
    wins: 26,
    draws: 8,
    losses: 6,
    titles: 2,
  },
  {
    userId: "user-6",
    championshipsPlayed: 5,
    matchesPlayed: 27,
    wins: 13,
    draws: 7,
    losses: 7,
    titles: 1,
  },
  {
    userId: "user-7",
    championshipsPlayed: 4,
    matchesPlayed: 23,
    wins: 9,
    draws: 5,
    losses: 9,
    titles: 0,
  },
  {
    userId: "user-8",
    championshipsPlayed: 4,
    matchesPlayed: 21,
    wins: 6,
    draws: 4,
    losses: 11,
    titles: 0,
  },
];

export const sampleVideos: VideoHighlight[] = [
  {
    id: "video-1",
    tournamentId: sampleTournament.id,
    matchId: "match-1",
    userId: "user-2",
    title: "Chute colocado no angulo",
    teamName: "Bragantino",
    description: null,
    videoUrl: "https://example.com/video.mp4",
    thumbnailUrl: null,
    approvalStatus: "approved",
    votesCount: 18,
    isGoalAwardWinner: false,
    createdAt: "2026-03-22T00:00:00Z",
  },
];

export const sampleTrophies: Trophy[] = [
  {
    id: "trophy-1",
    tournamentId: sampleTournament.id,
    userId: "user-organizer",
    category: "champion",
    title: "Campeao da Summer Cup 2025",
    imageUrl: null,
    awardedAt: "2025-12-18T00:00:00Z",
  },
];
