import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  layoutRoot: {
    flex: 1,
    backgroundColor: "#050C13",
  },
  centerGlow: {
    position: "absolute",
    borderRadius: 9999,
    backgroundColor: "rgba(132, 220, 255, 0.08)",
    shadowColor: "#8BD8FF",
    shadowOpacity: 0.28,
    shadowRadius: 120,
  },
  gridVertical: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: "#9ADFFF",
  },
  gridHorizontal: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "#9ADFFF",
  },
  vanishingPointWrap: {
    position: "absolute",
    left: "50%",
    bottom: 70,
    width: 2,
    height: "58%",
    marginLeft: -1,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  vanishingRay: {
    position: "absolute",
    bottom: 0,
    width: 1,
    height: "100%",
    backgroundColor: "#A4E7FF",
  },
  diamondOutline: {
    position: "absolute",
    borderWidth: 1,
    borderColor: "rgba(130, 208, 255, 0.11)",
    transform: [{ rotate: "45deg" }],
  },
  diamondOutlineSoft: {
    position: "absolute",
    borderWidth: 1,
    borderColor: "rgba(130, 208, 255, 0.08)",
    transform: [{ rotate: "45deg" }],
  },
  shapeBarGreen: {
    position: "absolute",
    backgroundColor: "rgba(162, 255, 170, 0.16)",
    transform: [{ rotate: "-32deg" }],
    borderRadius: 2,
  },
  shapeBarLight: {
    position: "absolute",
    backgroundColor: "rgba(255,255,255,0.24)",
    transform: [{ rotate: "65deg" }],
    borderRadius: 2,
  },
  shapePlate: {
    position: "absolute",
    backgroundColor: "rgba(217, 230, 237, 0.2)",
    transform: [{ rotate: "-8deg" }],
    borderRadius: 2,
  },
  wordmarkWrap: {
    position: "absolute",
    left: "50%",
    top: "39%",
    width: 320,
    height: 140,
    marginLeft: -160,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.32,
  },
  wordmarkDiamond: {
    position: "absolute",
    width: 110,
    height: 110,
    borderWidth: 1,
    borderColor: "rgba(188, 244, 255, 0.35)",
    transform: [{ rotate: "45deg" }],
    backgroundColor: "rgba(188, 244, 255, 0.04)",
  },
  wordmarkGlow: {
    position: "absolute",
    width: 220,
    height: 48,
    borderRadius: 999,
    backgroundColor: "rgba(111, 238, 220, 0.18)",
    shadowColor: "#7CF5E8",
    shadowOpacity: 0.85,
    shadowRadius: 34,
  },
  wordmarkLine: {
    position: "absolute",
    bottom: 8,
    width: 220,
    height: 2,
    backgroundColor: "rgba(173, 241, 255, 0.88)",
    shadowColor: "#A8F2FF",
    shadowOpacity: 0.7,
    shadowRadius: 14,
  },
  particle: {
    position: "absolute",
    borderRadius: 999,
    backgroundColor: "#E4FBFF",
    shadowColor: "#D4F8FF",
    shadowOpacity: 0.8,
    shadowRadius: 8,
  },
  bottomGlowLine: {
    position: "absolute",
    left: "8%",
    right: "8%",
    bottom: 74,
    height: 2,
    backgroundColor: "rgba(132, 227, 255, 0.72)",
    shadowColor: "#9DEFFF",
    shadowOpacity: 0.8,
    shadowRadius: 16,
  },
  tabBarTopLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(130, 214, 255, 0.2)",
  },
  tabButton: {
    marginHorizontal: 3,
    borderRadius: 18,
  },
  tabInner: {
    borderRadius: 18,
    overflow: "hidden",
    position: "relative",
  },
  tabInnerIdle: {
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  tabInnerHover: {
    shadowColor: "#FF2D4D",
    shadowOpacity: 0.16,
    shadowRadius: 18,
  },
  tabInnerSelected: {
    shadowColor: "#FF2D4D",
    shadowOpacity: 0.28,
    shadowRadius: 24,
  },
  activeSheen: {
    position: "absolute",
    left: "-12%",
    top: 0,
    bottom: 0,
    width: "124%",
  },
  activeTopEdge: {
    position: "absolute",
    left: 18,
    right: 18,
    top: 0,
    height: 2,
    borderBottomLeftRadius: 999,
    borderBottomRightRadius: 999,
    backgroundColor: "rgba(255,198,205,0.52)",
  },
  activeLeadingGlow: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 64,
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  activeTrailingGlow: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 42,
    backgroundColor: "rgba(0,0,0,0.18)",
  },
  stroke: {
    borderWidth: 1,
    borderRadius: 18,
  },
  strokeIdle: {
    borderColor: "rgba(152,194,212,0.18)",
  },
  strokeInteractive: {
    borderColor: "rgba(255,173,182,0.46)",
  },
  content: {
    flex: 1,
    justifyContent: "center",
  },
});
